# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c4230619d37b0381b1c1a031e7eb0f8bbe3f271d14e2dbbc44192695893300d75fdd2e2492c313b5bdff7be797937d38c0fa267a780d280971972e7cef3eca

test:
  secret_key_base: c3672a90e113f7df996a8c1dbe854bef1dbe1d7ca04a4257632ca30b3132a49492f6e4099176b176ef6ed46bb44a8d2d21bb877be52ae4979b295378aec9082e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
